name: hello-world
on: [push]
jobs:
  hello-world-job: 
    
    runs-on: ubutu-latest

    steps: 
      - name: check our repository code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
      
    
